### ISSUE TITLE
How is the visualization tool in CBEngine implemented?

### ISSUE THREAD

**Issue by wybiacx** [CityBrainLab/CityBrainLab#1]
![](https://cblab-documentation.readthedocs.io/en/latest/_images/imageonline-gifspeed-6207245.gif)

Can you tell me how this gif is made?

**Comment by CityBrainLab** [comment]
Thank you for your attention. At the end of this week, we will update the documentation and release the visualization tool. Please keep track of our documentation.

**Comment by wybiacx** [comment]
> 
That's good. thanks for your reply.
