### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by zhiyongc** [CityBrainLab/CityBrainLab#2]
Hi, I tried to install using source code. After running 

```
cd ./core
pip install -e ./
```

I keep receiving the following error. 

  

> cmake_version = LooseVersion(re.search(r'version\s*([\d.]+)', out.decode()).group(1))
>     Traceback (most recent call last):
>       File "<string>", line 2, in <module>
>       File "<pip-setuptools-caller>", line 34, in <module>
>       File "F:\Projects\CityBrainLab\CBEngine\core\setup.py", line 60, in <module>
>         setup(
>       File "C:\Users\123\.conda\envs\cblab\lib\site-packages\setuptools\__init__.py", line 87, in setup
>         return distutils.core.setup(**attrs)
>       File "C:\Users\123\.conda\envs\cblab\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
>         return run_commands(dist)
>       File "C:\Users\123\.conda\envs\cblab\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
>         dist.run_commands()
>       File "C:\Users\123\.conda\envs\cblab\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
>         self.run_command(cmd)
>       File "C:\Users\123\.conda\envs\cblab\lib\site-packages\setuptools\dist.py", line 1208, in run_command
>         super().run_command(command)
>       File "C:\Users\123\.conda\envs\cblab\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
>         cmd_obj.run()
>       File "C:\Users\123\.conda\envs\cblab\lib\site-packages\setuptools\command\develop.py", line 34, in run
>         self.install_for_development()
>       File "C:\Users\123\.conda\envs\cblab\lib\site-packages\setuptools\command\develop.py", line 114, in install_for_development
>         self.run_command('build_ext')
>       File "C:\Users\123\.conda\envs\cblab\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
>         self.distribution.run_command(command)
>       File "C:\Users\123\.conda\envs\cblab\lib\site-packages\setuptools\dist.py", line 1208, in run_command
>         super().run_command(command)
>       File "C:\Users\123\.conda\envs\cblab\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
>         cmd_obj.run()
>       File "F:\Projects\CityBrainLab\CBEngine\core\setup.py", line 32, in run
>         self.build_extension(ext)
>       File "F:\Projects\CityBrainLab\CBEngine\core\setup.py", line 57, in build_extension
>         subprocess.check_call(['cmake', '--build', '.', '--target', 'cbengine'] + build_args, cwd=self.build_temp)
>       File "C:\Users\123\.conda\envs\cblab\lib\subprocess.py", line 364, in check_call
>         raise CalledProcessError(retcode, cmd)
>     subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'cbengine', '--config', 'Release', '--', '/m']' returned non-zero exit status 1.
>     [end of output]
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.

Do you have any idea about it ? Thanks

**Comment by CityBrainLab** [comment]
We feel sorry that CBLab does not support Windows currently. That's why the error comes into being.
