### ISSUE TITLE
There seems to be a problem with flow generator code

### ISSUE THREAD

**Issue by wybiacx** [CityBrainLab/CityBrainLab#3]
in `CityBrainLab/CBData/input_data_transformation/flow/trafficGenerator.py`.
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/24806554/211963448-81b46b90-bea0-4ca0-a274-9a4e0deed71c.png">

The bbox variable is not used.

**Comment by CityBrainLab** [comment]
Thank you for your question. The variable 'bbox' is exactly a third wheel in our code that we will remove soon. The generator will generate traffic flow based on the range of latitude and longitude according to the loaded road network.

**Comment by CityBrainLab** [comment]
Now, this problem has been fixed.
