### ISSUE TITLE
Problems caused by visualization operation

### ISSUE THREAD

**Issue by MPHarryZhang** [CityBrainLab/CityBrainLab#4]
![44628d957c84b1eaa0b4d50b443124f](https://user-images.githubusercontent.com/44745773/225538967-25244b5d-5629-4cdd-a617-95115148bdb4.jpg)
I like this project very much, CBEngine can run normally, but when I run the application scenario of traffic signal control and try to visualize the result (I added the simulator visualization code according to the document requirements), an error on the picture is reported, no matter This problem will occur whether it is running fixed time, maxpressure or dqn, can you tell me what causes it? How to solve it?

**Comment by CityBrainLab** [comment]
What files do you copy from _report_log_addr_ to _ui/src/log_ ?

**Comment by MPHarryZhang** [comment]
> What files do you copy from _report_log_addr_ to _ui/src/log_ ?

All files in the folder include lightinfo.json, roadinfo.json, and timex.json. I found that timex.json does not have one for each step, but it may be generated at intervals such as time.json, time10.json, and time20.json like this.

**Comment by CityBrainLab** [comment]
Try setting the report_log_rate in the config file (e.g. manhattan.cfg) as 1 and you will obtain timeX.json(s) with one interval. This may fix this problem. The ui is currently not supporting visualization of multi-interval data.

**Comment by MPHarryZhang** [comment]
> Try setting the report_log_rate in the config file (e.g. manhattan.cfg) as 1 and you will obtain timeX.json(s) with one interval. This may fix this problem. The ui is currently not supporting visualization of multi-interval data.

Thank you very much.

**Comment by BackMountainDevil** [comment]
hello， guys. Could you please transerfer the [ui](https://drive.google.com/file/d/1ez3FDA0HL2XjGqiWgB5JSjbP8F29dXI1/view) to Baidu Netdisk?
